---
# Deployment with this template : kubectl apply -n argocd -f application.yaml
# Else : argocd app create guestbook --repo https://github.com/elea-dufresne/argocd-example-apps.git --path guestbook --dest-server https://kubernetes.default.svc --dest-namespace default --helm-set-string 'image.tag=${ARGOCD_APP_REVISION}'
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    - argocd-image-updater.argoproj.io/image-list: gcr.io/heptio-images/ks-guestbook-demo:*
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: guestbook
    repoURL: https://github.com/elea-dufresne/argocd-example-apps.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.tag
          value: $ARGOCD_APP_REVISION